export const data = [
  {
    os: ["aji"],
    cz: ["i"],
    en: [""],
    alternatives: ["také", "rovněž"],
  },
  {
    os: ["amoleta"],
    cz: ["palačinka"],
    en: [""],
    alternatives: [],
  },
  {
    os: ["balamutit"],
    cz: ["klamat"],
    en: [""],
    alternatives: ["obelhávat", "podvádět", "tahat za nos"],
  },
  {
    os: ["baňa"],
    cz: ["rána"],
    en: [""],
    alternatives: ["facka"],
  },
  {
    os: ["baňka"],
    cz: ["vánoční koule"],
    en: [""],
    alternatives: ["ozdoba na stromek"],
  },
  {
    os: ["bebech"],
    cz: ["zbytečná věc"],
    en: [""],
    alternatives: ["přebytečná věc"],
  },
  {
    os: ["bedrunka"],
    cz: ["slunéčko sedmitečné"],
    en: [""],
    alternatives: [],
  },
  {
    os: ["bo"],
    cz: ["protože"],
    en: ["because"],
    alternatives: [],
  },
  {
    os: ["buchat"],
    cz: ["měnit"],
    en: ["change"],
    alternatives: [],
  },
  {
    os: ["bulač"],
    cz: ["záškolák"],
    en: [""],
    alternatives: ["člověk, co chodí za školu"],
  },
  {
    os: ["bulat"],
    cz: ["chodit za školu"],
    en: [""],
    alternatives: [],
  },
  {
    os: ["cukle"],
    cz: ["nazouváky"],
    en: [""],
    alternatives: ["pantofle", "obuv bez paty"],
  },
  {
    os: ["cycek"],
    cz: ["prso"],
    en: ["boob"],
    alternatives: [],
  },
  {
    os: ["cyp"],
    cz: ["nemotorný horník"],
    en: [""],
    alternatives: [],
  },
  {
    os: ["cypovina"],
    cz: ["hloupost"],
    en: [""],
    alternatives: ["blbost"],
  },
  {
    os: ["čobol"],
    cz: ["Slovák"],
    en: [""],
    alternatives: [],
  },
  {
    os: ["čupni"],
    cz: ["Dřepni si"],
    en: [""],
    alternatives: [],
  },
  {
    os: ["domaknut se"],
    cz: ["dozvědět se"],
    en: [""],
    alternatives: [],
  },
  {
    os: ["dupa"],
    cz: ["zadek"],
    en: ["ass"],
    alternatives: ["prdel", "těžko dostupné místo"],
  },
  {
    os: ["garnýž"],
    cz: ["ta tyč, na které visí záclony"],
    alternatives: [],
  },
  {
    os: ["fasovat"],
    cz: ["obdržet"],
    en: [""],
    alternatives: ["dostat"],
  },
  {
    os: ["fárat"],
    cz: ["přemýšlet"],
    en: [""],
    alternatives: ["sjíždět do dolu", "uvažovat", "zamýšlet se"],
  },
  {
    os: ["fifrat"],
    cz: ["nimrat se v jídle"],
    en: [""],
    alternatives: [],
  },
  {
    os: ["fusekle"],
    cz: ["ponožky"],
    en: [""],
    alternatives: [],
  },
  {
    os: ["chlampat"],
    cz: ["pít"],
    en: [""],
    alternatives: ["pít přes míru", "pít hltavě"],
  },
  {
    os: ["chlustat"],
    cz: ["plivat"],
    en: [""],
    alternatives: [],
  },
  {
    os: ["kaj robiš"],
    cz: ["kde pracuješ"],
    en: [""],
    alternatives: [],
  },
  {
    os: ["karabáč"],
    cz: ["pomlázka"],
    en: [""],
    alternatives: [],
  },
  {
    os: ["kobzole"],
    cz: ["brambory"],
    en: [""],
    alternatives: [],
  },
  {
    os: ["krýgl"],
    cz: ["půllitr"],
    en: [""],
    alternatives: [],
  },
  {
    os: ["křak"],
    cz: ["křoví"],
    en: [""],
    alternatives: [],
  },
  {
    os: ["kypat"],
    cz: ["bryndat"],
    en: [""],
    alternatives: [],
  },
  {
    os: ["lajznout si"],
    cz: ["dovolit si"],
    en: [""],
    alternatives: [],
  },
  {
    os: ["luchat"],
    cz: ["pršet"],
    en: [""],
    alternatives: ["lít"],
  },
  {
    os: ["majtky"],
    cz: ["kalhotky"],
    en: [""],
    alternatives: [],
  },
  {
    os: ["majznout"],
    cz: ["praštit"],
    en: [""],
    alternatives: ["bouchnout", "udeřit"],
  },
  {
    os: ["maras"],
    cz: ["já vlastně ani nevím"],
    en: [""],
    alternatives: [],
  },
  {
    os: ["máš recht"],
    cz: ["máš pravdu"],
    en: [""],
    alternatives: [],
  },
  {
    os: ["olačka"],
    cz: ["kondom"],
    en: [""],
    alternatives: ["prezervativ"],
  },
  {
    os: ["plytký"],
    cz: ["mělký"],
    en: [""],
    alternatives: ["nehluboký"],
  },
  {
    os: ["puntek"],
    cz: ["poklopec"],
    en: [""],
    alternatives: [],
  },
  {
    os: ["půlka"],
    cz: ["panák"],
    en: [""],
    alternatives: [],
  },
  {
    os: ["rifle"],
    cz: ["džíny"],
    en: [""],
    alternatives: ["džínsy", "texasky"],
  },
  {
    os: ["rondl"],
    cz: ["kruhový objezd"],
    en: [""],
    alternatives: [],
  },
  {
    os: ["rožni"],
    cz: ["rozsviť"],
    en: [""],
    alternatives: [],
  },
  {
    os: ["rygol"],
    cz: ["strouha"],
    en: [""],
    alternatives: ["škarpa", "příkop"],
  },
  {
    os: ["ščur"],
    cz: ["potkan"],
    en: [""],
    alternatives: [],
  },
  {
    os: ["škráň"],
    cz: ["tvář"],
    en: [""],
    alternatives: ["líčko", "líce"],
  },
  {
    os: ["šolichat"],
    cz: ["věnovat se jen povrchně"],
    en: [""],
    alternatives: [],
  },
  {
    os: ["štangle"],
    cz: ["tyč"],
    en: [""],
    alternatives: ["tyč na kole", "palice salámu"],
  },
  {
    os: ["štekle"],
    cz: ["podpatky"],
    en: [""],
    alternatives: [],
  },
  {
    os: ["štelovat"],
    cz: ["nastavovat"],
    en: [""],
    alternatives: [],
  },
  {
    os: ["štrample"],
    cz: ["punčocháče"],
    en: [""],
    alternatives: [],
  },
  {
    os: ["šufánek"],
    cz: ["naběračka"],
    en: [""],
    alternatives: [],
  },
  {
    os: ["tadyk"],
    cz: ["zde"],
    en: ["here"],
    alternatives: ["tu", "tady", "zde"],
  },
  {
    os: ["udolat"],
    cz: ["přemoct"],
    en: [""],
    alternatives: ["přeprat"],
  },
  {
    os: ["vaječina"],
    cz: ["míchaná vajíčka"],
    en: [""],
    alternatives: ["míchaná vejce"],
  },
  {
    os: ["vybulit"],
    cz: ["spadnout"],
    en: [""],
    alternatives: [],
  },
  {
    os: ["zavázet"],
    cz: ["překážet"],
    en: [""],
    alternatives: ["zaclánět"],
  },
  {
    os: ["žďorb"],
    cz: ["haraburdí"],
    en: [""],
    alternatives: [],
  },
];
