export const data = [
  {
    ostrava: "bo",
    cz: "protože",
    en: "because",
    alternatives: [],
  },
  {
    ostrava: "buchat",
    cz: "měnit",
    en: "change",
    alternatives: [],
  },
  {
    ostrava: "bulat",
    cz: "chodit za školu",
    en: "",
    alternatives: [],
  },
  {
    ostrava: "cukle",
    cz: "nazouváky",
    en: "",
    alternatives: ["pantofle", "obuv bez paty"],
  },
  {
    ostrava: "dupa",
    cz: "zadek",
    en: "ass",
    alternatives: ["prdel", "těžko dostupné místo"],
  },
  {
    ostrava: "garnýž",
    cz: "ta tyč, na které visí záclony",
    alternatives: [],
  },
  {
    ostrava: "fusekle",
    cz: "ponožky",
    en: "",
    alternatives: [],
  },
  {
    ostrava: "kobzole",
    cz: "brambory",
    en: "",
    alternatives: [],
  },
  {
    ostrava: "krýgl",
    cz: "půllitr",
    en: "",
    alternatives: [],
  },
  {
    ostrava: "křak",
    cz: "křoví",
    en: "",
    alternatives: [],
  },
  {
    ostrava: "majtky",
    cz: "kalhotky",
    en: "",
    alternatives: [],
  },
  {
    ostrava: "majznout",
    cz: "praštit",
    en: "",
    alternatives: ["bouchnout", "udeřit"],
  },
  {
    ostrava: "maras",
    cz: "já vlastně ani nevím",
    en: "",
    alternatives: [],
  },
  {
    ostrava: "půlka",
    cz: "panák",
    en: "",
    alternatives: ["štamprle"],
  },
  {
    ostrava: "rondl",
    cz: "kruhový objezd",
    en: "",
    alternatives: [],
  },
  {
    ostrava: "rygol",
    cz: "strouha",
    en: "",
    alternatives: ["škarpa", "příkop"],
  },
  {
    ostrava: "štangle",
    cz: "tyč",
    en: "",
    alternatives: ["tyč na kole", "palice salámu"],
  },
  {
    ostrava: "štekle",
    cz: "podpatky",
    en: "",
    alternatives: [],
  },
  {
    ostrava: "štrample",
    cz: "punčocháče",
    en: "",
    alternatives: [],
  },
  {
    ostrava: "šufánek",
    cz: "naběračka",
    en: "",
    alternatives: [],
  },
  {
    ostrava: "udolat",
    cz: "přemoct",
    en: "",
    alternatives: ["přeprat"],
  },
  {
    ostrava: "vaječina",
    cz: "míchaná vajíčka",
    en: "",
    alternatives: ["míchaná vejce"],
  },
  {
    ostrava: "vybulit",
    cz: "spadnout",
    en: "",
    alternatives: [""],
  },
  {
    ostrava: "zavázet",
    cz: "překážet",
    en: "",
    alternatives: ["zaclánět"],
  },
];
