export const data = [
  {
    os: ["aji"],
    cz: ["i", "také", "rovněž"],
    en: [""],
    explanation:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam gravida purus ut risus blandit, sed interdum metus tristique. Proin vitae felis nec ante eleifend venenatis id ut odio. Integer vel diam a felis interdum cursus sed nec nulla.",
  },
  {
    os: ["amoleta"],
    cz: ["palačinka"],
    en: [""],
    explanation:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam gravida purus ut risus blandit, sed interdum metus tristique. Proin vitae felis nec ante eleifend venenatis id ut odio. Integer vel diam a felis interdum cursus sed nec nulla.",
  },
  {
    os: ["balamutit"],
    cz: ["klamat", "obelhávat", "podvádět", "tahat za nos"],
    en: [""],
    explanation:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam gravida purus ut risus blandit, sed interdum metus tristique. Proin vitae felis nec ante eleifend venenatis id ut odio. Integer vel diam a felis interdum cursus sed nec nulla.",
  },
  {
    os: ["baňa"],
    cz: ["rána", "facka"],
    en: [""],
    explanation:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam gravida purus ut risus blandit, sed interdum metus tristique. Proin vitae felis nec ante eleifend venenatis id ut odio. Integer vel diam a felis interdum cursus sed nec nulla.",
  },
  {
    os: ["baňka"],
    cz: ["vánoční koule", "ozdoba na stromek"],
    en: [""],
    explanation: "",
  },
  {
    os: ["bebech"],
    cz: ["zbytečná věc", "přebytečná věc"],
    en: [""],
    explanation: "",
  },
  {
    os: ["bedrunka"],
    cz: ["slunéčko sedmitečné"],
    en: [""],
    explanation: "",
  },
  {
    os: ["bo"],
    cz: ["protože"],
    en: ["because"],
    explanation: "",
  },
  {
    os: ["buchat"],
    cz: ["měnit"],
    en: ["change"],
    explanation: "",
  },
  {
    os: ["bulač"],
    cz: ["záškolák", "člověk, co chodí za školu"],
    en: [""],
    explanation: "",
  },
  {
    os: ["bulat"],
    cz: ["chodit za školu"],
    en: [""],
    explanation: "",
  },
  {
    os: ["cukle"],
    cz: ["nazouváky", "pantofle", "obuv bez paty"],
    en: [""],
    explanation: "",
  },
  {
    os: ["cycek"],
    cz: ["prso"],
    en: ["boob"],
    explanation: "",
  },
  {
    os: ["cyp"],
    cz: ["nemotorný horník"],
    en: [""],
    explanation: "",
  },
  {
    os: ["cypovina"],
    cz: ["hloupost", "blbost"],
    en: [""],
    explanation: "",
  },
  {
    os: ["čobol"],
    cz: ["Slovák"],
    en: [""],
    explanation: "",
  },
  {
    os: ["čupni"],
    cz: ["Dřepni si"],
    en: [""],
    explanation: "",
  },
  {
    os: ["domaknut se"],
    cz: ["dozvědět se"],
    en: [""],
    explanation: "",
  },
  {
    os: ["dupa"],
    cz: ["zadek", "prdel", "těžko dostupné místo"],
    en: ["ass"],
    explanation: "",
  },
  {
    os: ["garnýž"],
    cz: ["ta tyč, na které visí záclony"],
    en: [],
    explanation: "",
  },
  {
    os: ["fasovat"],
    cz: ["obdržet"],
    en: [""],
    explanation: "",
  },
  {
    os: ["fárat"],
    cz: ["přemýšlet", "sjíždět do dolu", "uvažovat", "zamýšlet se"],
    en: [""],
    explanation: "",
  },
  {
    os: ["fifrat"],
    cz: ["nimrat se v jídle"],
    en: [""],
    explanation: "",
  },
  {
    os: ["fusekle"],
    cz: ["ponožky", "fusky"],
    en: [""],
    explanation: "",
  },
  {
    os: ["chlampat"],
    cz: ["pít", "pít přes míru", "pít hltavě"],
    en: [""],
    explanation: "",
  },
  {
    os: ["chlustat"],
    cz: ["plivat"],
    en: [""],
    explanation: "",
  },
  {
    os: ["kaj robiš"],
    cz: ["kde pracuješ"],
    en: [""],
    explanation: "",
  },
  {
    os: ["karabáč"],
    cz: ["pomlázka"],
    en: [""],
    explanation: "",
  },
  {
    os: ["kobzole"],
    cz: ["brambory"],
    en: [""],
    explanation: "",
  },
  {
    os: ["krýgl"],
    cz: ["půllitr"],
    en: [""],
    explanation: "",
  },
  {
    os: ["křak"],
    cz: ["křoví"],
    en: [""],
    explanation: "",
  },
  {
    os: ["kypat"],
    cz: ["bryndat"],
    en: [""],
    explanation: "",
  },
  {
    os: ["lajznout si"],
    cz: ["dovolit si"],
    en: [""],
    explanation: "",
  },
  {
    os: ["luchat"],
    cz: ["pršet", "lít"],
    en: [""],
    explanation: "",
  },
  {
    os: ["luchec"],
    cz: ["silný déšť", "slejvák", "déšť"],
    en: [""],
    explanation: "",
  },
  {
    os: ["majtky"],
    cz: ["kalhotky"],
    en: [""],
    explanation: "",
  },
  {
    os: ["majznout"],
    cz: ["praštit", "bouchnout", "udeřit"],
    en: [""],
    explanation: "",
  },
  {
    os: ["maras"],
    cz: ["já vlastně ani nevím"],
    en: [""],
    explanation: "",
  },
  {
    os: ["máš recht"],
    cz: ["máš pravdu"],
    en: [""],
    explanation: "",
  },
  {
    os: ["olačka"],
    cz: ["kondom", "prezervativ"],
    en: [""],
    explanation: "",
  },
  {
    os: ["plytký"],
    cz: ["mělký", "nehluboký"],
    en: [""],
    explanation: "",
  },
  {
    os: ["puntek"],
    cz: ["poklopec"],
    en: [""],
    explanation: "",
  },
  {
    os: ["půlka"],
    cz: ["panák"],
    en: [""],
    explanation: "",
  },
  {
    os: ["rifle"],
    cz: ["džíny", "džínsy", "texasky"],
    en: [""],
    explanation: "",
  },
  {
    os: ["rondl"],
    cz: ["kruhový objezd"],
    en: [""],
    explanation: "",
  },
  {
    os: ["rožni"],
    cz: ["rozsviť"],
    en: [""],
    explanation: "",
  },
  {
    os: ["rygol"],
    cz: ["strouha", "škarpa", "příkop"],
    en: [""],
    explanation: "",
  },
  {
    os: ["ščur"],
    cz: ["potkan"],
    en: [""],
    explanation: "",
  },
  {
    os: ["škráň"],
    cz: ["tvář", "líčko", "líce"],
    en: [""],
    explanation: "",
  },
  {
    os: ["šolichat"],
    cz: ["věnovat se jen povrchně"],
    en: [""],
    explanation: "",
  },
  {
    os: ["štangle"],
    cz: ["tyč", "tyč na kole", "palice salámu"],
    en: [""],
    explanation: "",
  },
  {
    os: ["štekle"],
    cz: ["podpatky"],
    en: [""],
    explanation: "",
  },
  {
    os: ["štelovat"],
    cz: ["nastavovat"],
    en: [""],
    explanation: "",
  },
  {
    os: ["štrample"],
    cz: ["punčocháče"],
    en: [""],
    explanation: "",
  },
  {
    os: ["šufánek"],
    cz: ["naběračka"],
    en: [""],
    explanation: "",
  },
  {
    os: ["tadyk"],
    cz: ["zde", "tu", "tady", "zde"],
    en: ["here"],
    explanation: "",
  },
  {
    os: ["udolat"],
    cz: ["přemoct", "přeprat"],
    en: [""],
    explanation: "",
  },
  {
    os: ["vaječina"],
    cz: ["míchaná vajíčka", "míchaná vejce"],
    en: [""],
    explanation: "",
  },
  {
    os: ["vybulit"],
    cz: ["spadnout"],
    en: [""],
    explanation: "",
  },
  {
    os: ["zavázet"],
    cz: ["překážet", "zaclánět"],
    en: [""],
    explanation: "",
  },
  {
    os: ["žďorb"],
    cz: ["haraburdí"],
    en: [""],
    explanation: "",
  },
];
